apiVersion: v1
kind: Secret
metadata:
  name: login-cred
type: Opaque
data:
  username: bGFzdGxpbmU=
  password: QmhhcmF0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      name: hello-world
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: docker.io/bharathreddy44/lastline-cni-interview:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: login-cred
          mountPath: "/etc/secrets"
          readOnly: true
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi
        env:
        - name: PORT
          value: "8080"
        - name: DEBUG_MODE
          value: "0"
      volumes:
      - name: login-cred
        secret:
          secretName: login-cred
          items:
          - key: username
            path: username
            mode: 400
          - key: password
            path: password
            mode: 400
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-world
  name: hello-world
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: hello-world
  type: LoadBalancer
